name: daily-job-scout

on:
  schedule:
    - cron: "0 6 * * *"  # 06:00 UTC daily
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run
        env:
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          MAIL_FROM: ${{ secrets.MAIL_FROM }}
          MAIL_TO: ${{ secrets.MAIL_TO }}
          KEYWORDS: ${{ secrets.KEYWORDS }}
          LEAD_EMAIL_DOMAINS_BLOCKLIST: ${{ secrets.LEAD_EMAIL_DOMAINS_BLOCKLIST }}
          MAX_PAGES_PER_SITE: ${{ secrets.MAX_PAGES_PER_SITE }}
          TIMEOUT_SECONDS: ${{ secrets.TIMEOUT_SECONDS }}
        run: |
          python main.py
      - name: Upload CSV artifacts
        uses: actions/upload-artifact@v4
        with:
          name: job-scout-output
          path: out/*.csv
